CHROMIUM: iwl7000: mvm: fix SAR compilation without CONFIG_ACPI
Builds with CONFIG_ACPI disabled fail as follows.

drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c: In function 'iwl_mvm_sar_init':
drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c:1598:9: error:
	'struct iwl_mvm' has no member named 'sar_chain_a_profile'
drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c:1598:37: error:
	'struct iwl_mvm' has no member named 'sar_chain_b_profile'

because the structure members are only available with CONFIG_ACPI.

Signed-off-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
iwl7000-tree: ab43749751e1f994b1712758312ac8c542fe0693