samsung_pwm: fix build for CONFIG_CLKSRC_SAMSUNG_PWM=n
If CONFIG_PWM_SAMSUNG=y and CONFIG_CLKSRC_SAMSUNG_PWM=n next-20130626
build fails with the following error:

drivers/pwm/pwm-samsung.c:89:19: error: static declaration of ‘samsung_pwm_lock’ follows non-static declaration
include/clocksource/samsung_pwm.h:23:19: note: previous declaration of ‘samsung_pwm_lock’ was here

It is caused by commit 9ebe293 ("pwm: Add new pwm-samsung driver").

Fix it by adding missing ifdef.

Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Tomasz Figa <tomasz.figa@gmail.com>
Cc: Kukjin Kim <kgene.kim@samsung.com>
Signed-off-by: Kyungmin Park <kyungmin.park@samsung.com>
Signed-off-by: Bartlomiej Zolnierkiewicz <b.zolnierkie@samsung.com>

Posted upstream at:
    https://patchwork.kernel.org/patch/2787271/

BUG=chrome-os-partner:19401
TEST=Kernel builds when new samsung-pwm driver is added.

Change-Id: I4b8e823d296cc1fa307d520c5317cd74bb8b29a6
Signed-off-by: Andrew Bresticker <abrestic@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/65090
Reviewed-by: Olof Johansson <olofj@chromium.org>