UPSTREAM: drivers/usb: add missing GENERIC_HARDIRQS dependencies
Add a couple of missing GENERIC_HARDIRQS dependencies to fix link
errors like below on s390:

ERROR: "devm_request_threaded_irq" [drivers/usb/gadget/mv_udc.ko] undefined!

Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 5273afe359f700ac28bf8e9d63d733dbe0483e62)

Change-Id: If38fdb22b246f143ca1283985d1e9c2819432a0d
Signed-off-by: Vivek Gautam <gautam.vivek@samsung.com>