CHROMIUM: drm: nouveau: initialize channel pointer
Removes this compiler warning:
nv50_instmem.c:206:27: error: 'chan' may be used uninitialized in
this function

The variable 'chan' is implicitly initialized by passing to
nv50_channel_new()

This is not upstreamable as the structure of the nouveau driver has
changed in 3.8.

BUG=chromium-os:5542
TEST=emerge-x86-generic chromeos-kernel, make sure this warning doesn't
appear.

Change-Id: I753c4f160ecb8068d2bacae904bd2114df687a75
Signed-off-by: Simon Que <sque@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/42359
Reviewed-by: Mandeep Singh Baines <msb@chromium.org>