UPSTREAM: ASoC: max98090: Fix checkpatch errors related to spacing
Fixes the following type of checkpatch errors:
ERROR: "foo * bar" should be "foo *bar"

BUG=chrome-os-partner:18720, chrome-os-partner:22590
TEST=Builds
TEST=Built and booted on snow-rev5 board.
Tested audio with browser as well as aplay utility.

Signed-off-by: Sachin Kamat <sachin.kamat@linaro.org>
Signed-off-by: Mark Brown <broonie@opensource.wolfsonmicro.com>
(cherry picked from linux-next commit
	4ca74feb6ceb3031e8cf9ef88dedb3ebb984a59a)

Signed-off-by: Andrew Bresticker <abrestic@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/57627
Reviewed-by: Simon Glass <sjg@chromium.org>
(cherry picked from commit 37f75ac20e572a792bf6100004edcc8bb253076d)

Change-Id: I94a1b3826480016512dc41f226f34fed15f926e0
Signed-off-by: Padmavathi Venna <padma.v@samsung.com>
Reviewed-on: https://chromium-review.googlesource.com/169286
Reviewed-by: Doug Anderson <dianders@chromium.org>
Commit-Queue: Doug Anderson <dianders@chromium.org>
Tested-by: Doug Anderson <dianders@chromium.org>