CHROMIUM: iwl7000: 32 bit images are not supported
Attempts to build iwl7000 images for 32 bit kernels results in:

./usr/include/drm/i915_drm.h:33: userspace cannot reference function or variable defined in the kernel
ERROR: "__udivdi3" [drivers/net/wireless/iwl7000/iwlwifi/xvt/iwlxvt.ko] undefined!
ERROR: "__umoddi3" [drivers/net/wireless/iwl7000/iwlwifi/xvt/iwlxvt.ko] undefined!

Mark the offending code (IWL7000_XVT) as dependent on 64 bit builds.

BUG=chromium:833502
TEST=Build i386:allmodconfig

Change-Id: I5fd0ff3a11da8eef9b231609dc834734914c5bd6
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1014291
Reviewed-by: Kirtika Ruchandani <kirtika@chromium.org>
(cherry picked from commit 1733fcca17ec1531cad0e1d7a9d93fe9de726a30)
Reviewed-on: https://chromium-review.googlesource.com/1103877
Commit-Ready: Kirtika Ruchandani <kirtika@chromium.org>
Tested-by: Kirtika Ruchandani <kirtika@chromium.org>