UPSTREAM: irqchip: irq-gic: Fix checkpatch errors
Fixes the following errors:
ERROR: do not initialise statics to 0 or NULL
ERROR: space required after that ',' (ctx:VxV)

Signed-off-by: Sachin Kamat <sachin.kamat@linaro.org>
Signed-off-by: Olof Johansson <olof@lixom.net>
(cherry picked from commit 46f101df788b38fafa08e85dcbf85d3bff6c1ea3)

BUG=chrome-os-partner:19820
TEST=Builds.  These are only style changes.

Change-Id: I605f06d0fd1d2adf02e71ee23401d1096c450c4e
Signed-off-by: Andrew Bresticker <abrestic@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/59937
Reviewed-by: Doug Anderson <dianders@chromium.org>