Revert "pinctrl: exynos: add irq_set_wake function"
drivers/pinctrl/pinctrl-exynos.c: In function 'exynos_wkup_irq_set_wake':
drivers/pinctrl/pinctrl-exynos.c:314:86: error: expected ')' before 'eint_num'
drivers/pinctrl/pinctrl-exynos.c:314:86: warning: format '%d' expects a matching 'int' argument [-Wformat]
drivers/pinctrl/pinctrl-exynos.c:314:86: warning: format '%s' expects a matching 'char *' argument [-Wformat]
drivers/pinctrl/pinctrl-exynos.c:314:86: warning: format '%ld' expects a matching 'long int' argument [-Wformat]

This reverts commit 770793925556a03b478bbd5c91eee9d6c113e093

Change-Id: I08842041d5314b7fb78d510210e6fa5a1aee6e47
Reviewed-on: https://gerrit.chromium.org/gerrit/51255
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>