MALI: Return kbase_tmem_{re}size failure in a base_backing_threshold_status
The ioctl uses result_subcode, which is a plain u32, to pass the failure
reason (if any) back to userspace.  However, internally the
kbase_tmem_{re}size() functions return the error code as an
enum base_backing_threshold_status.  An enum isn't necessarily u32, so the
compiler complains.

Fixes the following compiler warnings when compiling with GCC 4.8
chromeos-kernel-next-3.8.11-r851: drivers/gpu/arm/t6xx/kbase/src/linux/mali_kbase_core_linux.c: In function 'kbase_dispatch':
chromeos-kernel-next-3.8.11-r851: drivers/gpu/arm/t6xx/kbase/src/linux/mali_kbase_core_linux.c:570:4: error: passing argument 5 of 'kbase_tmem_set_size' from incompatible pointer type [-Werror]
chromeos-kernel-next-3.8.11-r851:     ukh->ret = kbase_tmem_set_size(kctx, set_size->gpu_addr, set_size->size, &set_size->actual_size, &set_size->result_subcode);
chromeos-kernel-next-3.8.11-r851:     ^
chromeos-kernel-next-3.8.11-r851: In file included from drivers/gpu/arm/t6xx/kbase/src/../../kbase/src/common/mali_kbase.h:51:0,
chromeos-kernel-next-3.8.11-r851:                  from drivers/gpu/arm/t6xx/kbase/src/linux/mali_kbase_core_linux.c:23:
chromeos-kernel-next-3.8.11-r851: drivers/gpu/arm/t6xx/kbase/src/../../kbase/src/common/mali_kbase_mem.h:397:12: note: expected 'enum base_backing_threshold_status * const' but argument is of type 'u32 *'
chromeos-kernel-next-3.8.11-r851:  mali_error kbase_tmem_set_size(kbase_context *kctx, mali_addr64 gpu_addr, u32 size, u32 * const actual_size, base_backing_threshold_status * const failure_reason);
chromeos-kernel-next-3.8.11-r851:             ^
chromeos-kernel-next-3.8.11-r851: drivers/gpu/arm/t6xx/kbase/src/linux/mali_kbase_core_linux.c:586:4: error: passing argument 5 of 'kbase_tmem_resize' from incompatible pointer type [-Werror]
chromeos-kernel-next-3.8.11-r851:     ukh->ret = kbase_tmem_resize(kctx, resize->gpu_addr, resize->delta, &resize->actual_size, &resize->result_subcode);
chromeos-kernel-next-3.8.11-r851:     ^
chromeos-kernel-next-3.8.11-r851: In file included from drivers/gpu/arm/t6xx/kbase/src/../../kbase/src/common/mali_kbase.h:51:0,
chromeos-kernel-next-3.8.11-r851:                  from drivers/gpu/arm/t6xx/kbase/src/linux/mali_kbase_core_linux.c:23:
chromeos-kernel-next-3.8.11-r851: drivers/gpu/arm/t6xx/kbase/src/../../kbase/src/common/mali_kbase_mem.h:382:12: note: expected 'enum base_backing_threshold_status * const' but argument is of type 'u32 *'
chromeos-kernel-next-3.8.11-r851:  mali_error kbase_tmem_resize(kbase_context *kctx, mali_addr64 gpu_addr, s32 delta, u32 * const size, base_backing_threshold_status * const failure_reason);
chromeos-kernel-next-3.8.11-r851:             ^
chromeos-kernel-next-3.8.11-r851: cc1: all warnings being treated as errors

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chromium:309916
TEST=compiles clean w/ GCC version 4.7 and 4.8

Change-Id: I3505d4de2f35028d8e6aaee649a3f05d3cab1436
Reviewed-on: https://chromium-review.googlesource.com/173856
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Luis Lozano <llozano@chromium.org>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>