CHROMIUM: net: mac80211: deleted unused variables
net/mac80211/mlme.c: In function 'ieee80211_rx_mgmt_beacon':
net/mac80211/mlme.c:2471:5: error: unused variable 'deauth_buf' [-Werror=unused-variable]
net/mac80211/mlme.c: In function 'ieee80211_sta_connection_lost':
net/mac80211/mlme.c:2753:31: error: unused variable 'ifmgd' [-Werror=unused-variable]

Deleted the unused variables ifmgd and deauth_buf.

BUG=chromium:237705
TEST=compile

Change-Id: Id842be4686f41acfc31b0edd6c67faf69808df52
Signed-off-by: Paul Taysom <taysom@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/63113
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>