UPSTREAM: ACPI / fan: fix fan driver compile error when CONFIG_PM_SLEEP is undefined
The ACPI fan driver defines acpi_fan_suspend() and acpi_fan_resume()
when CONFIG_PM_SLEEP is defined. This results in the following compile
errors when CONFIG_PM_SLEEP is undefined:

drivers/acpi/fan.c:60:8: error: ‘acpi_fan_suspend’ undeclared here (not in a function)
drivers/acpi/fan.c:60:8: error: ‘acpi_fan_resume’ undeclared here (not in a function)

Signed-off-by: Shuah Khan <shuah.kh@samsung.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit b108e0ea94a33f85590959a7a7fbcfd6f8ea8ab6)
Signed-off-by: Kaiyen Chang <kaiyen.chang@intel.com>

BUG=chrome-os-partner:28265
TEST=undefine CONFIG_PM_SLEEP and then build the kernel. Should no
longer see the compile errors.

Change-Id: Ia3f9b3b8322661a86692a0763927fe89f9f1fd80
Reviewed-on: https://chromium-review.googlesource.com/236536
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Benson Leung <bleung@chromium.org>
Commit-Queue: Kaiyen Chang <kaiyen.chang@intel.com>
Tested-by: Kaiyen Chang <kaiyen.chang@intel.com>