usb: dwc3: gadget: Fix build break due to missing 'err' label
On enabling 'CONFIG_USB_GADGET' and 'CONFIG_USB_DWC3_GADGET'
we are hitting following build error:
drivers/usb/dwc3/gadget.c: In function 'dwc3_gadget_init':
drivers/usb/dwc3/gadget.c:2592:1: error: label 'err5' defined but not used [-Werror=unused-label]

Following commit introduced this:
50bfa96 UPSTREAM: usb: dwc3: gadget: introduce and use enable/disable irq methods
Fix it.

BUG=none
TEST=kernel compiles fine for both peach_pit and daisy boards on
enabling CONFIG_USB_GADGET and CONFIG_USB_DWC3_GADGET.

Change-Id: I1b85096dee90a6d6c872476666060f767b6a4512
Signed-off-by: Vivek Gautam <gautam.vivek@samsung.com>
Reviewed-on: https://chromium-review.googlesource.com/174252
Reviewed-by: Julius Werner <jwerner@chromium.org>