UPSTREAM: clk: tegra: fix enum tegra114_clk to match binding
A gap exists in the binding's clock ID definitions. Fix the clock driver
to be consistent. This allows pclk to be looked up through device tree
and prevents:

ERROR: could not get clock /pmc:pclk(0)

Signed-off-by: Stephen Warren <swarren@nvidia.com>
(cherry picked from commit 964ea47572b89589b61b553e44bbe9907d4f12a6)
(cherry-picked from:
	git://git.kernel.org/pub/scm/linux/kernel/git/swarren/linux-tegra.git)
Signed-off-by: Olof Johansson <olofj@chromium.org>